### PR TITLE
Better landing page added

### PR DESCRIPTION
**Pull request by ketan270**
<h1>Before:</h1>

Screenshot 2024-10-06 151147
 

<h1>After:</h1>

Screenshot 2024-10-06 151417
Screenshot 2024-10-06 151428

Merge My pull request for Hacktoberfest 24

### CODE REVIEW

**Comment by ketan270** [comment]
ISSUE #14

**Comment by strivedi4u** [comment]
Great

**Comment by strivedi4u** [comment]
🚀 Follow me, 💬 Join the WhatsApp Group, and ⭐ Star the Repo to support our journey together!

**Comment by ketan270** [comment]
Please add hacktoberfest labels

**Pull request merged**
